[package]
name = "ceres"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "ceres"
path = "src/lib.rs"


[dependencies]
common = { path = "../common" }
jupiter = { path = "../jupiter" }
callisto = { path = "../jupiter/callisto" }
mercury = { path = "../mercury" }
venus = { path = "../venus" }
ganymede = { path = "../ganymede" }

anyhow = { workspace = true }
tokio = { workspace = true, features = ["net"] }
axum = { workspace = true }
tracing = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
clap = { workspace = true, features = ["derive"] }
chrono = { workspace = true }
futures = { workspace = true }
bytes = { workspace = true }
async-trait = { workspace = true }
rand = { workspace = true }
