[package]
name = "storage"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "storage"
path = "src/lib.rs"


[dependencies]
common = { path = "../common" }
entity = { path = "./entity" }
idgenerator = "2.0.0"
aws-config = { version = "1.1.5", features = ["behavior-version-latest"] }
aws-sdk-s3 = "1.15.0"
aws-smithy-types = "1.1.6"

anyhow = { workspace = true }
async-trait = { workspace = true }
tracing = { workspace = true }
chrono = { workspace = true }
sha256 = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
futures = { workspace = true }
sea-orm = { workspace = true, features = [
    "sqlx-postgres",
    "sqlx-mysql",
    "runtime-tokio-rustls",
    "macros",
] }
thiserror = { workspace = true }
bytes = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["macros"] }
