[package]
name = "orion"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { workspace = true, features = ["macros"]}
tokio = { workspace = true, features = ["rt-multi-thread", "fs", "process"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
serde = { workspace = true, features = ["derive"] }
reqwest = { workspace = true, features = ["json"] }
uuid = { workspace = true, features = ["v7"]}
futures-util = "0.3.30"
dashmap = "6.1.0"
once_cell = "1.19.0"
sea-orm = { workspace = true, features = [
    "sqlx-postgres",
    "runtime-tokio-rustls",
    "macros",
] }
dotenvy = "0.15.7"