[package]
name = "mega"
version = "0.1.0"
edition = "2021"
keywords = ["git", "monorepo", "decentralized"]
license = "MIT OR Apache-2.0"
readme = "README.md"

[workspace]
members = [
    ".",
    "gateway",
    "common",
    "mercury",
    "jupiter",
    "venus",
    "ceres",
    "libra",
]

exclude = ["craft"]

[[bin]]
name = "mega"
path = "mega/src/main.rs"

[dependencies]
gateway = { workspace = true }
common = { workspace = true }
ceres = { workspace = true }
serde = { workspace = true, features = ["derive"] }
tokio = { workspace = true, features = ["macros"] }
clap = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tracing-appender = { workspace = true }
thiserror = { workspace = true }
rand = { workspace = true }
smallvec = { workspace = true }
config = { workspace = true }

[dev-dependencies]
reqwest = { version = "0.12.4", features = ["stream", "json"] }
russh = { workspace = true }
russh-keys = { workspace = true }
async-trait = { workspace = true }
bytes = { workspace = true }
go-defer = { workspace = true }
env_logger = "0.11.3"
futures-util = "0.3.30"
tokio-util = "0.7.11"
git2 = "0.18.3"
toml = "0.8.12"


[workspace.dependencies]
gateway = { path = "gateway" }
common = { path = "common" }
mercury = { path = "mercury" }
jupiter = { path = "jupiter" }
venus = { path = "venus" }
ceres = { path = "ceres" }
callisto = { path = "jupiter/callisto" }
anyhow = "1.0.83"
serde = "1.0.201"
serde_json = "1.0.117"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
tracing-appender = "0.2"
thiserror = "1.0.60"
rand = "0.8.5"
smallvec = "1.13.2"
tokio = "1.37.0"
tokio-test = "0.4.4"
clap = "4.5.4"
async-trait = "0.1.80"
bytes = "1.6.0"
chrono = "0.4.38"
sha1 = "0.10.6"
sha256 = "1.5"
futures = "0.3.30"
go-defer = "0.1.0"
russh = "0.43.0"
russh-keys = "0.43.0"
axum = "0.7.5"
tower-http = "0.5.2"
tower = "0.4.13"
hex = "0.4.3"
sea-orm = "0.12.15"
flate2 = "1.0.28"
bstr = "1.9.1"
colored = "2.1.0"
idgenerator = "2.0.0"
num_cpus = "1.16.0"
config = "0.14.0"


[build-dependencies]
shadow-rs = "0.27.1"
