[package]
name = "mega"
version = "0.1.0"
edition = "2021"

[workspace]
members = [".", "gateway", "git", "common", "storage", "p2p", "kvcache", "delta", "mercury"]
exclude = ["mda", "craft", "fuse"]

[dependencies]
gateway = { path = "gateway" }
common = { path = "common" }
p2p = { path = "p2p" }
config = "0.13"
serde_json = "1.0"
anyhow = "1.0"
lazy_static = "1.4.0"
shadow-rs = "0.25.0"
dotenvy = "0.15.7"
tracing-subscriber = "0.3"
thiserror = "1.0"
rand = "0.8.5"
smallvec = "1.11"
tokio = { version = "1.35.1", features = ["macros"] }
clap = { version = "4.4.11", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }

[build-dependencies]
shadow-rs = "0.25.0"
