[package]
name = "mega"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    ".",
    "gateway",
    "git",
    "common",
    "storage",
    "p2p",
    "kvcache",
    "delta",
    "mercury",
    "jupiter",
    "jupiter/callisto",
    "venus",
    "ganymede", 
    "ceres",
    "libra",
]
exclude = ["craft", "fuse"]

[dependencies]
gateway = { path = "gateway" }
common = { path = "common" }
p2p = { path = "p2p" }
git = { path = "git" }
config = "0.14"
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
anyhow = { workspace = true }
dotenvy = { workspace = true }
tracing-subscriber = { workspace = true }
thiserror = { workspace = true }
rand = { workspace = true }
smallvec = { workspace = true }
tokio = { workspace = true, features = ["macros"] }
clap = { workspace = true, features = ["derive"] }

[dev-dependencies]
reqwest = { version = "0.12.0", features = ["stream", "json"] }
env_logger = "0.11.0"
futures-util = "0.3.30"
tokio-util = "0.7.10"
git2 = "0.18.1"
toml = "0.8.8"
russh = { workspace = true }
russh-keys = { workspace = true }
async-trait = { workspace = true }
bytes = { workspace = true }
go-defer = { workspace = true }


[workspace.dependencies]
anyhow = "1.0.81"
serde = { version = "1.0.197" }
serde_json = "1.0.115"
dotenvy = "0.15.7"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
thiserror = "1.0.58"
rand = "0.8.5"
smallvec = "1.13.2"
tokio = { version = "1.37.0" }
tokio-test = "0.4.4"
clap = { version = "4.5.4" }
async-trait = "0.1.79"
bytes = "1.6.0"
chrono = "0.4.37"
sha1 = "0.10.6"
sha256 = "1.5"
futures = "0.3.30"
go-defer = "0.1.0"
russh = "0.43.0"
russh-keys = "0.43.0"
axum = "0.7.5"
hex = "0.4.3"
sea-orm = "0.12.15"
redis = "0.24.0"
flate2 = "1.0.28"
bstr = "1.9.1"
colored = "2.1.0"
idgenerator = "2.0.0"

[build-dependencies]
shadow-rs = "0.27.0"
