[package]
name = "mega"
version = "0.1.0"
edition = "2021"

[workspace]
members = [".", "gateway", "git", "common", "storage", "p2p", "kvcache", "delta", "mercury"]
exclude = ["mda", "craft", "fuse"]

[dependencies]
gateway = { path = "gateway" }
common = { path = "common" }
p2p = { path = "p2p" }
git = { path = "git" }
config = "0.13"
serde = { version = "1.0.195", features = ["derive"] }
serde_json = "1.0.111"
anyhow = "1.0.79"
lazy_static = "1.4.0"
shadow-rs = "0.26.0"
dotenvy = "0.15.7"
tracing-subscriber = "0.3"
thiserror = "1.0"
rand = "0.8.5"
smallvec = "1.11"
tokio = { version = "1.35.1", features = ["macros"] }
clap = { version = "4.4.11", features = ["derive"] }



[dev-dependencies]
reqwest = {version = "0.11.23", features = ["stream", "json"]}
env_logger = "0.10.1"
futures-util = "0.3.30"
tokio-util = "0.7.10"
go-defer = "0.1.0"
bytes = "1.5.0"
git2 = "0.18.1"


[build-dependencies]
shadow-rs = "0.26.0"
