[package]
name = "mega"
version = "0.1.0"
edition = "2021"

[dependencies]
config = "0.13.3"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.89"
clap = { version = "4.1.6", features = ["derive"] }
anyhow = "1.0.69"
