[package]
name = "mega"
version = "0.1.0"
edition = "2021"

[workspace]
members = [".","gateway", "git", "core", "storage"]

[dependencies]
config = "0.13.3"
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
clap = { version = "4.2.7", features = ["derive"] }
anyhow = "1.0.69"
lazy_static = "1.4.0"
shadow-rs = "0.21.0"
gateway = { path = "gateway" }
mega-core = { path = "core" }
tokio = {version = "1.28.1", features = ["full"]}
dotenvy = "0.15.7"
tracing-subscriber = "0.3.17"

[build-dependencies]
shadow-rs = "0.21.0"
