[package]
name = "mega"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["gateway", "git"]

[dependencies]
config = "0.13.3"
serde = { version = "1.0.155", features = ["derive"] }
serde_json = "1.0.89"
clap = { version = "4.1.6", features = ["derive"] }
anyhow = "1.0.69"
lazy_static = "1.4.0"
shadow-rs = "0.21.0"
gateway = { path = "gateway" }
git = { path = "git" }

[build-dependencies]
shadow-rs = "0.21.0"