[package]
name = "mercury"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = { path = "../common"}
serde = {version = "1.0.193", features = ["derive"]} 
bstr = "1.8.0"
colored = "2.0.4"
sha1_smol = "1.0.0"
hex = "0.4.3"
thiserror = "1.0.50"