[package]
name = "mercury"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = { path = "../common" }
sha1_smol = "1.0.0"

serde = { workspace = true, features = ["derive"] }
bstr = { workspace = true }
hex = { workspace = true }
thiserror = { workspace = true }
flate2 = { workspace = true }
tracing = { workspace = true }
sha1 = { workspace = true }
colored = {workspace = true}
