[package]
name = "gateway"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "gateway"
path = "src/lib.rs"


[dependencies]
common = { path = "../common" }
jupiter = { path = "../jupiter" }
callisto = { path = "../jupiter/callisto" }
ganymede = { path = "../ganymede" }
ceres = { path = "../ceres" }
venus = { path = "../venus" }

regex = "1.10.3"
ed25519-dalek = { version = "2.1.1", features = ["pkcs8"] }

anyhow = { workspace = true }
tokio = { workspace = true, features = ["net"] }
axum = { workspace = true }
tower-http = { workspace = true, features = ["cors", "trace", "decompression-full"] }
tower = { workspace = true }
tracing = { workspace = true }
russh = { workspace = true, features = ["openssl"] }
russh-keys = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
clap = { workspace = true, features = ["derive"] }
chrono = { workspace = true }
futures = { workspace = true }
bytes = { workspace = true }
async-trait = { workspace = true }
