[package]
name = "gateway"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "gateway"
path = "src/lib.rs"


[dependencies]
git = {path = "../git"}
common = {path = "../common"}
storage = {path = "../storage"}
entity = { path = "../storage/entity" }
anyhow = "1.0.77"
axum = "0.7.3"
tower = "0.4.13"
tower-http = { version = "0.5.0", features = ["cors", "trace"] }
tokio = {version = "1.35", features = ["net"]}
regex = "1.10.2"
tracing = "0.1.40"
russh = { version = "0.40.2", features = ["openssl"]}
russh-keys = {version = "0.40.1"}
ed25519-dalek = {version = "2.1", features = ["pkcs8"]}
serde = "1.0"
serde_json = "1.0"
clap = { version = "4.4.11", features = ["derive"] }
chrono = "0.4"
futures = "0.3"
bytes = "1.5"
async-trait = "0.1"
