[package]
name = "gateway"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "gateway"
path = "src/lib.rs"


[dependencies]
git = {path = "../git"}
common = {path = "../common"}
storage = {path = "../storage"}
entity = { path = "../storage/entity" }
anyhow = "1.0.75"
axum = "0.7.2"
tower = "0.4.13"
tower-http = { version = "0.5.0", features = ["cors", "trace"] }
tokio = {version = "1.35", features = ["net"]}
regex = "1.9.1"
tracing = "0.1.37"
russh = { version = "0.40.2"}
russh-keys = "0.40.1"
ed25519-dalek = "2.0"
serde = "1.0.188"
serde_json = "1.0.105"
clap = { version = "4.4.11", features = ["derive"] }
chrono = "0.4.26"
jsonwebtoken = "9.2.0"
futures = "0.3.28"
bytes = "1.4.0"
async-trait = "0.1.74"
