[package]
name = "mega"
version = "0.1.0"
edition = "2021"
authors = ["Quanyi Ma <genedna@gmail.com>"]
keywords = ["git", "monorepo", "decentralized"]
license = "MIT OR Apache-2.0"
readme = "README.md"
build = "src/build.rs"

[[bin]]
name = "mega"
path = "src/main.rs"

[dependencies]
mono = { workspace = true }
jupiter = { workspace = true }
gateway = { workspace = true }
common = { workspace = true }
ceres = { workspace = true }
taurus = { workspace = true }
serde = { workspace = true, features = ["derive"] }
tokio = { workspace = true, features = ["macros"] }
clap = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tracing-appender = { workspace = true }
thiserror = { workspace = true }
rand = { workspace = true }
smallvec = { workspace = true }
config = { workspace = true }
shadow-rs = { workspace = true }
ctrlc = { workspace = true }

[dev-dependencies]
reqwest = { workspace = true, features = ["stream", "json"] }
russh = { workspace = true }
russh-keys = { workspace = true }
async-trait = { workspace = true }
bytes = { workspace = true }
go-defer = { workspace = true }
git2 = { workspace = true }
tempfile = { workspace = true }
serial_test = "3.1.1"
lazy_static = {workspace = true}

[build-dependencies]
shadow-rs = { workspace = true }
