[package]
name = "p2p"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "p2p"
path = "src/lib.rs"


[dependencies]
git = { path = "../git" }
storage = { path = "../storage" }
entity = { path = "../storage/entity" }
common = { path = "../common" }
kvcache = { path = "../kvcache" }
bytes = "1.5"
tokio = "1.35.1"
tracing = "0.1.40"
futures = "0.3.30"
futures-timer = "3.0.2"
async-std = { version = "1.12.0", features = ["attributes"] }
libp2p = { version = "0.53", features = ["dcutr", "kad", "yamux", "noise", "identify", "macros", "relay", "tcp", "async-std", "rendezvous", "request-response", "cbor", "secp256k1"] }
serde = { version = "1.0", features = ["derive"] }
clap = { version = "4.4.11", features = ["derive"] }
serde_json = "1.0"
async-trait = "0.1"
cbor4ii = { version = "0.3.1", features = ["serde1", "use_std"] }
redis = { version = "0.23", features = ["tokio-comp"] }
secp256k1 = { version = "0.27.0", features = ["serde", "bitcoin-hashes", "bitcoin-hashes-std", "rand"] }
axum = "0.7.2"


