[package]
name = "p2p"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "p2p"
path = "src/mod.rs"


[dependencies]
git = { path = "../git" }
database = { path = "../database" }
common = { path = "../common" }
clap = { version = "4.3.0", features = ["derive"] }
tracing = "0.1.37"
futures = "0.3.28"
futures-timer = "3.0.2"
async-std = { version = "1.10", features = ["attributes"] }
libp2p = { version = "0.52.1", features = ["dcutr", "kad", "yamux", "noise", "identify", "macros", "relay", "tcp", "async-std", "rendezvous", "request-response", "cbor"] }
serde = { version = "1.0", features = ["derive"] }
bytes = "1.4.0"
tokio = "1.28.1"
