[package]
name = "p2p"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "p2p"
path = "src/lib.rs"


[dependencies]
git = { path = "../git" }
storage = { path = "../storage" }
entity = { path = "../storage/entity" }
common = { path = "../common" }
kvcache = { path = "../kvcache" }
futures-timer = "3.0.2"
async-std = { version = "1.12.0", features = ["attributes"] }
libp2p = { version = "0.53", features = ["dcutr", "kad", "yamux", "noise", "identify", "macros", "relay", "tcp", "async-std", "rendezvous", "request-response", "cbor", "secp256k1"] }
cbor4ii = { version = "0.3.1", features = ["serde1", "use_std"] }
secp256k1 = { version = "0.27.0", features = ["serde", "bitcoin-hashes", "bitcoin-hashes-std", "rand"] }

bytes = {workspace = true}
tokio = {workspace = true}
tracing = {workspace = true}
futures = {workspace = true}
serde = { workspace = true, features = ["derive"] }
clap = { workspace = true, features = ["derive"] }
serde_json = {workspace = true}
async-trait = {workspace = true}
redis = { workspace = true, features = ["tokio-comp"] }
axum = {workspace = true}
