[package]
name = "libra"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
venus = { path = "../venus" }
mercury = { path = "../mercury" }
storage = { path = "../storage" }
ceres = { path = "../ceres" }
sea-orm = { workspace = true, features = [
    "sqlx-sqlite",
    "runtime-tokio-rustls",
    "macros",
] }
tokio = { workspace = true, features = ["rt-multi-thread", "rt", "macros"] }
sha1 = { workspace = true }
byteorder = "1.5.0"
clap = { workspace = true, features = ["derive"] }
color-backtrace = "0.6.1"
colored = "2.1.0"
chrono.workspace = true
path_abs = "0.5.1"
pathdiff = "0.2.1"
flate2 = { workspace = true }
tracing = { workspace = true }
tracing-subscriber ={ workspace = true }
url = "2.5.0"
reqwest = "0.12.4"
base64 = "0.22.1"

[target.'cfg(unix)'.dependencies] # only on Unix
pager = "0.16.0"

[dev-dependencies]
tokio = { workspace = true, features = ["macros"] }
tracing-test = "0.2.4"