[package]
name = "libra"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
venus = { path = "../venus" }
mercury = { path = "../mercury" }
storage ={ path = "../storage" }
sea-orm = { workspace = true, features = [
    "sqlx-sqlite",
    "runtime-tokio-rustls",
    "macros",
] }
tokio = { workspace = true, features = ["rt-multi-thread"] }
sha1 = { workspace = true }
byteorder = "1.5.0"
clap = { workspace = true, features = ["derive"] }
color-backtrace = "0.6.1"
colored = "2.1.0"

[dev-dependencies]
tokio = { workspace = true, features = ["macros"] }
