[package]
name = "libra"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "libra"
path = "src/main.rs"

[dependencies]
mercury = { workspace = true }
ceres = { workspace = true }
sea-orm = { workspace = true, features = [
    "sqlx-sqlite",
    "runtime-tokio-rustls",
    "macros",
] }
tokio = { workspace = true, features = ["rt-multi-thread", "rt", "macros"] }
clap = { workspace = true, features = ["derive"] }
flate2 = { workspace = true }
tracing = { workspace = true }
tracing-subscriber ={ workspace = true }
sha1 = { workspace = true }
bytes = { workspace = true }
chrono = { workspace = true }
futures = { workspace = true }
reqwest = { version = "0.12.4", features = ["stream"] }
tokio-util = { version = "0.7.11", features = ["io"] }
color-backtrace = "0.6.1"
colored = "2.1.0"
byteorder = "1.5.0"
path_abs = "0.5.1"
pathdiff = "0.2.1"
url = "2.5.0"
futures-util = "0.3.30"
rpassword = "7.3.1"


[target.'cfg(unix)'.dependencies] # only on Unix
pager = "0.16.0"

[dev-dependencies]
tokio = { workspace = true, features = ["macros"] }
tracing-test = "0.2.4"