name: 'Install Dependencies'
description: 'Install dependencies with caching support'

inputs:
  cache-key:
    description: 'Cache key for dependencies, usually "${{ github.run_id }}"'
    required: true
  platform:
    description: 'Platform (ubuntu-latest, windows-latest, macos-latest)'
    required: true

runs:
  using: "composite"
  steps:
    # Universal Initialization
    - name: Cache dependencies
      id: cache-restore
      uses: actions/cache@v3
      with:
        path: |
          /var/cache/apt/
          ~/Library/Caches/Homebrew
          C:\ProgramData\chocolatey\lib
        key: ${{ inputs.platform }}-sysdeps-${{ inputs.cache-key }}

    # ================ Platform-specific Initialization (Linux) ================
    - name: Install dependencies (Ubuntu)
      if: inputs.platform == 'ubuntu-latest'
      shell: bash
      run: |
        echo "deb http://gb.archive.ubuntu.com/ubuntu jammy main" | sudo tee -a /etc/apt/sources.list
        sudo apt update
        sudo apt install -y \
          git-lfs \
          libwebkit2gtk-4.1-dev \
          build-essential \
          curl \
          wget \
          file \
          libssl-dev \
          libgtk-3-dev \
          libayatana-appindicator3-dev \
          librsvg2-dev \
          libgtk-4-dev \
          libadwaita-1-0 \
          libadwaita-1-dev \
          fuse3 \
          libfuse3-dev \

    # ================ Platform-specific Initialization (macOS) ================
    - name: Set up Homebrew
      id: set-up-homebrew
      uses: Homebrew/actions/setup-homebrew@master

    # fuse not available on macOS
    - name: Install dependencies (macOS)
      if: inputs.platform == 'macos-latest'
      shell: bash
      run: |
        brew install \
          git-lfs \
          gtk4 \
          gtk+3 \
          libadwaita \
          openssl@3 \
          pkgconf \
          webkitgtk \
          librsvg \

    # =============== Platform-specific Initialization (Windows) ===============
    - name: Install dependencies (Windows)
      if: inputs.platform == 'windows-latest'
      uses: crazy-max/ghaction-chocolatey@v3
      with:
        args: install \
          openssl \
          git-lfs \
          pkgconfiglite \
          cmake \
          ninja \
          
    # ======================== Cache downloaded packages ========================
    - name: Cache downloaded packages
      id: cache-save
      uses: actions/cache@v3
      with:
        path: |
          /var/cache/apt/
          ~/Library/Caches/Homebrew
          C:\ProgramData\chocolatey\lib
        key: ${{ inputs.platform }}-sysdeps-${{ github.run_id }}
        restore-keys: |
          ${{ inputs.platform }}-sysdeps-
