[package]
name = "storage"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "storage"
path = "src/lib.rs"


[dependencies]
common = {path = "../common"}
entity = {path = "./entity"}
anyhow = "1.0"
async-trait = "0.1"
tracing = "0.1.40"
idgenerator = "2.0.0"
chrono = "0.4"
sha256 = "1.4"
serde = "1.0"
serde_json = "1.0"
futures = "0.3"
sea-orm = {version = "0.12", features = [
    "sqlx-postgres",
    "sqlx-mysql",
    "runtime-tokio-rustls",
    "macros",
]}
aws-config = {version = "1.1.1", features = ["behavior-version-latest"]}
aws-sdk-s3 = "1.11.0"
aws-smithy-types = "1.1.1"
thiserror = "1.0.52"
bytes = "1.5.0"

[dev-dependencies]
tokio = { version = "1.35.0", features = ["macros"] }