[package]
name = "delta"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha1 = "0.10.5"
diffs = "0.5.1"
thiserror = "1.0.47"

[features]
default = ["diff_mydrs"]
diff_mydrs = []
