[package]
name = "common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "common"
path = "src/mod.rs"

[dependencies]
anyhow = "1.0.75"
sea-orm = "0.12.2"
thiserror = "1.0.47"
clap = { version = "4.4.0", features = ["derive"] }
