[package]
name = "common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "common"
path = "src/lib.rs"

[dependencies]
axum = { workspace = true }
anyhow = { workspace = true }
sea-orm = { workspace = true }
thiserror = { workspace = true }
clap = { workspace = true, features = ["derive"] }
idgenerator = { workspace = true }
serde = { workspace = true }
config = { workspace = true }
envsubst = "0.2.1"
