[package]
name = "scorpio"
version = "0.1.0"
edition = "2021"

[dependencies]
libra = { path = "../libra" }
mercury = { path = "../mercury" }

toml = "0.8.19"
fuser = "0.14.0"
libc = "0.2.155"
log = "0.4.22"
radix_trie = "0.2.1"
signal-hook = "0.3.17"
tracing = "0.1.40"
serde_json = "1.0.117"
once_cell = "1.19.0"
arc-swap = "1.5"
reqwest =  { version = "0.12.5", features = ["json"] }
serde = { version = "1.0.203", features = ["derive"] }
fuse-backend-rs = { version = "0.12.0"}
tokio = { version = "1.38.1", features = ["full"] }
vm-memory = { version = "0.10", features = ["backend-mmap", "backend-bitmap"] }
env_logger = "0.11.5"

[features]
async-io = []

[workspace]
members = [ "client" ]
