[package]
name = "scorpio"
version = "0.1.0"
edition = "2021"

[dependencies]
libra = {path = "../libra"}
fuse-backend-rs = { version = "0.12.0"}
fuser = "0.14.0"
libc = "0.2.155"
log = "0.4.22"
radix_trie = "0.2.1" 
signal-hook = "0.3.17"
tracing = "0.1.40"
reqwest =  { version = "0.12.5", features = ["json"] }
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
once_cell = "1.19.0"
tokio = { version = "1.38.1", features = ["full"] }
arc-swap = "1.5"
vm-memory = { version = "0.10", features = ["backend-mmap", "backend-bitmap"] }
mercury = { path = "../mercury" }
toml = "0.8.19"
[features]
async-io = []

[workspace]
