url = "http://localhost:8000"
workspace = "/home/luxian/megadir/mount"
store_path = "/home/luxian/megadir/store"
git_author = "MEGA"
git_email = "admin@mega.org"

[[works]]
path = "third-part/buck-hello"
node = 8
hash = "5f70f0f460d92d73eac0ea09ef2edb3840bfc68f"
