git_author = "MEGA"
git_email = "admin@mega.org"
workspace = ""
store_path = ""
base_url = "http://localhost:8000"
config_file = "config.toml"
file_blob_endpoint = "http://localhost:8000/api/v1/file/blob"
lfs_url = "http://localhost:8000"
