[package]
name = "rust-third-party"
version = "0.1.0"
edition = "2021"

# Dummy target to keep Cargo happy
[[bin]]
name = "top"
path = "top/main.rs"

[dependencies]
rusty_vault = "0.2.1"
serde_json = "1.0.117"
go-defer = "0.1.0"
openssl = "0.10.68"
hex = "0.4.3"
lazy_static = "1.5.0"
bs58 = "0.5.1"
serde = { version = "1.0.117", features = ["derive"] }
secp256k1 = { version = "0.30.0" , features = ["serde", "rand","hashes"] }
tokio = {version = "1.43.0", features = ["full"]}
async-std = "1.13.0"

anyhow = "1.0.93"
axum = "0.8.1"
clap = { version = "4.5.28", features = ["derive"] }
base64 = "0.22.1"
dotenvy = "0.15.7"
tracing = "0.1.40"
thiserror = "2.0.11"
async-trait = "0.1.86"
reqwest = "0.12.12"
assert_cmd = "2.0.16"

sea-orm = { version = "1.1.4", features = ["sqlx-postgres", "sqlx-mysql", "sqlx-sqlite"] }
envsubst = "0.2.1"
regex = "1.11.1"
rand = "0.9.0"
config = "0.15.7"
idgenerator = "2.0.0"