[package]
name = "callisto"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "callisto"
path = "src/lib.rs"

[dependencies]
common = { path = "../../common" }

serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
chrono = { workspace = true }
sea-orm = { workspace = true, features = ["sqlx-postgres", "sqlx-mysql", "sqlx-sqlite"] }
